spring:
  application:
    name: gateway
  profiles:
    default: oauth2
server:
  port: 4040
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}
logging:
  level:
    org.springframework.cloud.gateway.filter.factory: DEBUG
    io.github.resilience4j: DEBUG
    org.springframework.web: DEBUG