spring:
  kafka:
    listener:
     # el ack genera como un aviso de que ya leyo el mensaje
      ack-mode: manual_immediate
    consumer:
     # se refiera al kafka 
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
     # Las siguientes 2 lineas es para indicar como vamos a deserealizar los mensajes que llegue (key:value)
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: circuitbreaker

  datasource:
    username: ${db.username}
    password: ${db.password}
    url: ${db.url}
    hikari:
      maximum-pool-size: ${db.maximum-pool-size}
      connection-timeout: ${db.connection-timeout}

  application:
    name: companies-crud

  profiles:
    default: default

  config:
    import: "optional:configserver:http://localhost:7777"

server:
  servlet:
    context-path: /companies-crud
  port: 8081

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://localhost:4318/v1/traces
  metrics:
    distribution:
      percentiles:
        do.sleep.method.timed: 0.99, 0.95, 0.9, 0.7, 0.5
        http.server.requests: 0.99, 0.95, 0.9, 0.7, 0.5
      percentiles-histogram:
        do.sleep.method.timed: true
        http.server.requests: true
